# Site settings
title:          OOPSpam Blog
description:    "Learn how to protect your website from spam bots & manual spam."
url:            "https://www.oopspam.com"
baseurl:        "/blog"
copyright: "OOPSpam LLC"
logo: "https://www.oopspam.com/blog/assets/favicon-32x32.png"

# JSON-LD

languageCode:  "en-US"  

# Google Analytics
google_analytics: 11111

# Author
author:
  name:         OOPSpam
  url:          https://www.oopspam.com
  email:        contact@oopspam.com
  twitter:      oopspamapi

# Build settings
markdown:       kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-tagging-related_posts
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:     /:title
paginate:       12

# Excludes
exclude: 
  - Gemfile
  - Gemfile.lock
  - tale.gemspec
  - vendor/
  - .bundle/
  - node_modules/
  - .git/
  - .gitignore
  - README.md
  - LICENSE
  - "*.sh"

# Social networks
twitter:
  username: oopspamapi


collections:
  authors:
    output: true
